#!/bin/bash

LOCK=$HOME/.config/i3/lock

case "$1" in
    "lock")
        bash $LOCK
        ;;
    "exit")
        i3-msg exit
        ;;
    "suspend")
        bash $LOCK
        systemctl suspend
        ;;
    "hibernate")
        bash $LOCK
        systemctl hibernate 
        ;;
    "reboot")
        systemctl reboot
        ;;
    "shutdown")
        systemctl poweroff -i
        ;;
esac