#!/bin/bash

if [[ "$(xkb-switch)" != "us" ]]
then
    xkb-switch -n
fi
TMPBG=/tmp/screen.png
LOCK=/home/sami/.config/i3/scripts/lock.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

if [ "$(xrandr --query | grep 'DP-1-1' | cut -c 8-16)" = "connected" ]
then 
    ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -filter_complex "boxblur=5:1" -vframes 1 $TMPBG -loglevel quiet
else
    ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=5:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet
fi

i3lock -i $TMPBG -u
rm $TMPBG
